# Timing constraints

# System clock is generated by MMCM by module crg.
# It's timing constraints are in clkgen_50mhz.xdc

# JTAG
create_clock -period 100.000 -name TCK -waveform {0.000 50.000} [get_pins {u_dmi_jtag/i_dmi_jtag_tap/i_tap_dtmcs/TCK}]

set_clock_groups -asynchronous -group {TCK}
